import { ProjectCardProps } from '@/components/shared/project-table';

export const projects: (ProjectCardProps & { categories: string[] })[] = [
  {
    title: 'Papara Invest',
    href: 'https://invest.papara.com/',
    shortDescription: 'An investment platform for the Papara ecosystem.',
    status: 'On Hold (Live)',
    stack: ['Next.js', 'Fastify'],
    year: 2025,
    image: '/papara_logo.jpg',
    categories: ['web'],
  },
  {
    title: 'Planla',
    href: 'https://www.planla.io/',
    shortDescription: 'Easy-to-use and fun story point estimations.',
    status: 'Maintained',
    stack: ['Next.js', 'Express.js', 'Socket.IO'],
    year: 2024,
    image: '/planla_logo.png',
    categories: ['web'],
  },
  {
    title: 'Type-Streak',
    href: 'https://type-streak.emirguvenni.com/',
    shortDescription: 'A streak-based typing game focused on speed and accuracy.',
    status: 'Maintained',
    stack: ['Vue.js'],
    year: 2021,
    image: 'type-streak_logo.jpg',
    unoptimizedImage: true,
    categories: ['web'],
  },
  {
    title: 'otofix.io',
    shortDescription: 'CRM system for car/motorcycle repair shops.',
    status: 'Under Development',
    stack: ['Next.js', 'Express.js', 'Prisma'],
    year: 2026,
    categories: ['web'],
  },
  {
    title: 'Borsa Bot',
    href: 'https://github.com/EmirGuvenni/Borsa-Bot',
    shortDescription: 'A Discord bot that fetches the conversion rate of TRY to USD and EUR.',
    status: 'Archived',
    stack: ['TypeScript', 'Discord.js', 'Node.js'],
    year: 2021,
    categories: ['bot'],
  },
  {
    title: 'Random Botsons',
    href: 'https://github.com/EmirGuvenni/random-botsons',
    shortDescription: 'A Discord bot that rolls the dice, tosses a coin, that sort of things.',
    status: 'Archived',
    stack: ['JavaScript', 'Discord.js', 'Node.js'],
    year: 2020,
    categories: ['bot'],
  },
];
